# Autogenerated file by entering the following command line:   coffee /home/gmto/gmt_releases/gmt_release_1.8.2-1/bin/ethercatgen all /home/pkurkdjian/work/modules/ocs_example_dcs/model/example_ctrl_pkg/example_ctrl_fb.coffee
module.exports =

    master: [
        {id: 0, rate: 1000 }
    ]

    domains: [
        { id: 0, master: 0, rate_factor: 1 }
        { id: 1, master: 0, rate_factor: 10 }
    ]

    modules: [
        # 1) Copy the PDO mapping names you need from the comment to the pdo_mapping array. If you keep the default mapping, keep the array empty.
        # 2) Make sure you do not select two incompatible PDO mappings.
        { name: "dig_inp"    ,  position: 1,  alias: 0,  type: "EL1008",  master_id: 0,  pdo_mapping: [ "Channel 1", "Channel 2", "Channel 3", "Channel 4", "Channel 5", "Channel 6", "Channel 7", "Channel 8" ] }
        { name: "motor"      ,  position: 6,  alias: 0,  type: "EL7041",  master_id: 0,  pdo_mapping: [ "ENC Control compact", "STM Control", "STM Velocity", "ENC Status compact", "STM Status" ] }
    ]

    data_objects: [
        { name: "red_push_button"                   ,  type: "tx_pdo",  std_name: "Channel 1 : Input"                                ,  module: "dig_inp",  domain: 0}
        { name: "green_push_button"                 ,  type: "tx_pdo",  std_name: "Channel 2 : Input"                                ,  module: "dig_inp",  domain: 0}
        { name: "emergency_button"                  ,  type: "tx_pdo",  std_name: "Channel 3 : Input"                                ,  module: "dig_inp",  domain: 0}
        { name: "motor_enabled"                     ,  type: "tx_pdo",  std_name: "STM Status : Status__Ready to enable"             ,  module: "motor",  domain: 0}
        { name: "motor_ready"                       ,  type: "tx_pdo",  std_name: "STM Status : Status__Ready"                       ,  module: "motor",  domain: 0}
        { name: "motor_warning"                     ,  type: "tx_pdo",  std_name: "STM Status : Status__Warning"                     ,  module: "motor",  domain: 0}
        { name: "motor_error"                       ,  type: "tx_pdo",  std_name: "STM Status : Status__Error"                       ,  module: "motor",  domain: 0}
        { name: "motor_moving_positive"             ,  type: "tx_pdo",  std_name: "STM Status : Status__Moving positive"             ,  module: "motor",  domain: 0}
        { name: "motor_moving_negative"             ,  type: "tx_pdo",  std_name: "STM Status : Status__Moving negative"             ,  module: "motor",  domain: 0}
        { name: "motor_enable"                      ,  type: "rx_pdo",  std_name: "STM Control : Control__Enable"                    ,  module: "motor",  domain: 0}
        { name: "motor_reset"                       ,  type: "rx_pdo",  std_name: "STM Control : Control__Reset"                     ,  module: "motor",  domain: 0}
        { name: "motor_velocity"                    ,  type: "rx_pdo",  std_name: "STM Velocity : Velocity"                          ,  module: "motor",  domain: 0}
    ]
