# Autogenerated file by entering the following command line:   coffee /home/gmto/gmt_releases/gmt_release_1.8.2-1/bin/ethercatgen all /home/pkurkdjian/work/modules/ocs_example_dcs/model/example_ctrl_pkg/example_ctrl_fb.coffee
path = require 'path'
module.exports =
    catalog: [
      require path.resolve process.env.GMT_LOCAL, './etc/conf/example_dcs/EL1008_conf.coffee'   # Slave 0
      require path.resolve process.env.GMT_LOCAL, './etc/conf/example_dcs/EL7041_conf.coffee'   # Slave 1
    ]
